// <auto-generated />
using System;
using BloodWatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BloodWatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BloodWatchDbContext))]
    [Migration("20260226204734_AddReserveHistoryObservations")]
    partial class AddReserveHistoryObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.CollectionSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .HasColumnType("text")
                        .HasColumnName("access_code");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("district_code");

                    b.Property<string>("DistrictName")
                        .HasColumnType("text")
                        .HasColumnName("district_name");

                    b.Property<Guid?>("DonationCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_center_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_code");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_name");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnType("text")
                        .HasColumnName("municipality_code");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionHours")
                        .HasColumnType("text")
                        .HasColumnName("session_hours");

                    b.Property<string>("SessionTypeCode")
                        .HasColumnType("text")
                        .HasColumnName("session_type_code");

                    b.Property<string>("SessionTypeName")
                        .HasColumnType("text")
                        .HasColumnName("session_type_name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("StateCode")
                        .HasColumnType("text")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DonationCenterId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("SourceId", "SessionDate");

                    b.ToTable("collection_sessions", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.CurrentReserveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<DateOnly?>("ReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("reference_date");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_label");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId", "CapturedAtUtc");

                    b.HasIndex("SourceId", "RegionId", "MetricKey")
                        .IsUnique();

                    b.ToTable("current_reserves", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.DeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("EventId", "Status");

                    b.HasIndex("EventId", "SubscriptionId")
                        .IsUnique();

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.DonationCenterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("district_code");

                    b.Property<string>("DistrictName")
                        .HasColumnType("text")
                        .HasColumnName("district_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_code");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnType("text")
                        .HasColumnName("municipality_code");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PlusCode")
                        .HasColumnType("text")
                        .HasColumnName("plus_code");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("Schedule")
                        .HasColumnType("text")
                        .HasColumnName("schedule");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("SourceId", "InstitutionCode")
                        .IsUnique();

                    b.HasIndex("SourceId", "RegionId");

                    b.ToTable("donation_centers", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentReserveId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_reserve_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_key");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentReserveId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId", "CreatedAtUtc");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Key")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.ReserveHistoryObservationEntity", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("MetricKey")
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("reference_date");

                    b.Property<string>("StatusKey")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<short>("StatusRank")
                        .HasColumnType("smallint")
                        .HasColumnName("status_rank");

                    b.HasKey("SourceId", "RegionId", "MetricKey", "ReferenceDate", "StatusKey");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId", "MetricKey", "ReferenceDate");

                    b.HasIndex("SourceId", "StatusRank", "ReferenceDate");

                    b.HasIndex("SourceId", "RegionId", "MetricKey", "CapturedAtUtc")
                        .IsDescending(false, false, false, true);

                    b.ToTable("reserve_history_observations", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adapter_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastPolledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdapterKey")
                        .IsUnique();

                    b.ToTable("sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51abf65a-c68a-4bc7-b9f2-3f8f3a9bb2b1"),
                            AdapterKey = "pt-dador-ipst",
                            CreatedAtUtc = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portugal Dador/IPST"
                        });
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MetricFilter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_filter");

                    b.Property<string>("RegionFilter")
                        .HasColumnType("text")
                        .HasColumnName("region_filter");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_key");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SourceId", "IsEnabled");

                    b.HasIndex("SourceId", "ScopeType", "RegionFilter", "InstitutionId", "MetricFilter", "IsEnabled");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.CollectionSessionEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.DonationCenterEntity", "DonationCenter")
                        .WithMany("CollectionSessions")
                        .HasForeignKey("DonationCenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", "Region")
                        .WithMany("CollectionSessions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("CollectionSessions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationCenter");

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.CurrentReserveEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", "Region")
                        .WithMany("CurrentReserves")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("CurrentReserves")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.DeliveryEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("Deliveries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SubscriptionEntity", "Subscription")
                        .WithMany("Deliveries")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.DonationCenterEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", "Region")
                        .WithMany("DonationCenters")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("DonationCenters")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.CurrentReserveEntity", "CurrentReserve")
                        .WithMany("Events")
                        .HasForeignKey("CurrentReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", "Region")
                        .WithMany("Events")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("Events")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentReserve");

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("Regions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.ReserveHistoryObservationEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", "Region")
                        .WithMany("ReserveHistoryObservations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("ReserveHistoryObservations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.DonationCenterEntity", "Institution")
                        .WithMany("Subscriptions")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", "Source")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.CurrentReserveEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.DonationCenterEntity", b =>
                {
                    b.Navigation("CollectionSessions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.RegionEntity", b =>
                {
                    b.Navigation("CollectionSessions");

                    b.Navigation("CurrentReserves");

                    b.Navigation("DonationCenters");

                    b.Navigation("Events");

                    b.Navigation("ReserveHistoryObservations");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.SourceEntity", b =>
                {
                    b.Navigation("CollectionSessions");

                    b.Navigation("CurrentReserves");

                    b.Navigation("DonationCenters");

                    b.Navigation("Events");

                    b.Navigation("Regions");

                    b.Navigation("ReserveHistoryObservations");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BloodWatch.Infrastructure.Persistence.Entities.SubscriptionEntity", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
